export const jobOpenings = [
   {
      id: 1,
      title: "Montessori Teacher",
      department: "Teaching",
      location: "Accra, Ghana",
      summary: "Seeking an experienced Montessori teacher for our primary program.",
      description: "We are looking for a passionate Montessori teacher to guide our students through the primary curriculum. Responsibilities include lesson planning, classroom management, and fostering a nurturing learning environment. Qualifications: Bachelor's degree in Education, Montessori certification, and at least 3 years of experience.",
      applicationInstructions: "Please upload your resume and cover letter using the application form below.",
   },
   {
      id: 2,
      title: "Administrative Assistant",
      department: "Administration",
      location: "Accra, Ghana",
      summary: "Join our team as an Administrative Assistant to support daily operations.",
      description: "The Administrative Assistant will manage scheduling, communications, and general office tasks. Ideal candidates will have excellent organizational skills, proficiency in office software, and prior experience in a similar role.",
      applicationInstructions: "Submit your application online with a cover letter detailing your experience.",
   },
   {
      id: 3,
      title: "IT Support Specialist",
      department: "Information Technology",
      location: "Accra, Ghana",
      summary: "Provide technical support and ensure smooth IT operations across the school.",
      description: "The IT Support Specialist will handle system troubleshooting, software updates, and hardware maintenance. Requirements: Bachelor’s degree in Computer Science or related field, experience with network and system administration, and strong problem-solving skills.",
      applicationInstructions: "Include your resume and a brief description of your IT-related experience in your application.",
   },
   {
      id: 4,
      title: "School Counselor",
      department: "Student Support",
      location: "Accra, Ghana",
      summary: "Support students' academic and personal development as our School Counselor.",
      description: "Responsibilities include conducting one-on-one and group counseling sessions, developing academic plans, and coordinating with teachers and parents to address student needs. Qualifications: Master’s degree in Counseling or Psychology and experience working with students in an educational setting.",
      applicationInstructions: "Apply with a resume and a statement of your counseling philosophy.",
   },
   {
      id: 5,
      title: "Physical Education Instructor",
      department: "Physical Education",
      location: "Accra, Ghana",
      summary: "We are hiring a dedicated Physical Education Instructor to promote healthy lifestyles.",
      description: "The Physical Education Instructor will organize fitness activities, teach sports skills, and instill the importance of physical health. Requirements include a degree in Physical Education, experience coaching or teaching, and strong communication skills.",
      applicationInstructions: "Send your application, including a CV and a summary of your fitness philosophy, through our online form.",
   },
   {
      id: 6,
      title: "Librarian",
      department: "Library",
      location: "Accra, Ghana",
      summary: "Manage and enhance our library resources as the new school Librarian.",
      description: "Duties include organizing library materials, assisting students with research, and planning literary activities. Candidates should have a degree in Library Science and experience in an educational library setting.",
      applicationInstructions: "Please submit your CV and a brief cover letter explaining your interest in the role.",
   },
];
